apply plugin: 'com.android.library'

group = 'expo.modules.hardwarekeyboard'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(':expo-modules-core').projectDir.absolutePath, 'ExpoModulesCorePlugin.gradle')
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()
useDefaultAndroidSdkVersions()

android {
  namespace 'expo.modules.hardwarekeyboard'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
  lintOptions {
    abortOnError false
  }
}
